# Site settings
title: Hyeongger
email: dlgudrl1203@gmail.com
url: https://hyeongger.github.io
description: "안녕하세요. 이형기입니다."
keywords: "Product Manager, Data Scientist"
skills: "Data Analytics, System Analysis and Design, User Experience Design"
meta_author: Lee Hyeongger

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://www.instagram.com/hyeongger/
  - title: facebook
    url:
  - title: stack-overflow
    url: https://www.instagram.com/hyeongger/
  - title: bitbucket
    url: https://www.instagram.com/hyeongger/
  - title: github
    url: https://www.instagram.com/hyeongger/
    
# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
Contact: '연락처: 010-5719-7172 or <a href="dlgudrl1203@gmail.com">이메일</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
